cores: "4"
load-balancer: "10000"
cycle: "1"
processes:
  - pid: "1"
    time: "2019/10/05 20:59:15"
    priority: "1"
    tasks: 
      - "10"
      - "20"
      - "30"
      - "5"
      - "10"
      - "5"
  - pid: "2"
    time: "2019/10/05 21:59:15"
    priority: "1"
    tasks: 
      - "10"
      - "20"
      - "30"
      - "5"
      - "10"
      - "5"
  - pid: "3"
    time: "2019/10/05 20:59:15"
    priority: "1"
    tasks: 
      - "49"
      - "10"
      - "35"
      - "5"
      - "67"
      - "10"
  - pid: "10"
    time: "2019/10/05 20:59:15"
    priority: "4"
    tasks: 
      - "10"
      - "55"
      - "7"
      - "79"
      - "12"
      - "61"
  - pid: "5"
    time: "2019/10/05 20:59:15"
    priority: "1"
    tasks: 
      - "100"
      - "67"
      - "120"
      - "34"
      - "78"
      - "50"
  - pid: "6"
    time: "2019/10/05 20:59:15"
    priority: "1"
    tasks: 
      - "50"
      - "100"
      - "56"
      - "87"
      - "41"
      - "100"
      