cores: "4"
load-balancer: "5"
cycle: "1"
processes:
  - pid: "1"
    time: "2019/10/05 20:59:15"
    priority: "1"
    resources: 
      - "10"
      - "20"
      - "30"
      - "5"
      - "10"
      - "5"
  - pid: "2"
    time: "2019/10/05 21:59:15"
    priority: "1"
    resources: 
      - "10"
      - "20"
      - "30"
      - "5"
      - "10"
      - "5"
      